name: Docker

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Docker Buildx and publish
        uses: ilteoood/docker_buildx@master
        with:
          imageName: rsaikali/linkypy
          platform: linux/arm/v7
          dockerHubUser: ${{ secrets.DOCKER_HUB_LOGIN }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
          publish: true

