name: PEP8

on: [push]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: autopep8
        uses: peter-evans/autopep8@master
        with:
          args: --max-line-length=160 --recursive --in-place --aggressive --aggressive .